#!/bin/sh
x=$1
if ["$x" =~ [A-Z][a-z]{2,100} ]; then
echo "$x to imie"
elif [ "$x" =~ [0-9]{2}-[0-9]{3} ]; then
echo "$x to kod pocztowy"
elif [ "$x" =~ [A-z0-9]+\@[a-z0-9]{2,5}\.(com|pl) ]; then
echo "$x to email"
else
echo "Błąd"
fi
